[project]
name = "tddfa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
py-modules = ["FaceBoxes", "tddfa", "Sim3DR"]

